name: build On ubuntu 18.04
# This workflow is triggered on pushes to the repository. Modify and push this file, and should build.
on: [push]

jobs: 
    build:
        runs-on: ubuntu-18.04 #CUDA is very version coupled
        steps:
            - name: Install git-lfs
              run: sudo apt-get -y install git-lfs
            - name: Retrieve casacore latest stable version v3.1.2
              run: git clone --single-branch --branch v3.1.2 https://github.com/casacore/casacore.git
            - name: Install dependencies
              run: sudo apt-get install -y build-essential cmake gfortran g++ libncurses5-dev libreadline-dev flex bison libblas-dev liblapacke-dev libcfitsio-dev wcslib-dev libhdf5-serial-dev libfftw3-dev python-numpy libboost-python-dev libpython2.7-dev
            - name: Build casacore
              run: cd casacore && mkdir build && cd build && cmake -DUSE_FFTW3=ON -DUSE_OPENMP=ON -DUSE_HDF5=ON -DUSE_THREADS=ON .. && make -j 8 && sudo make install
            - name: Install cfitsio
              run: sudo apt-get -y install libcfitsio-dev
            - name: Install CUDA
              run: sudo wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && sudo apt-get update && sudo apt-get install cuda
            - name: Retrieve gpuvmem
              run: git clone --single-branch --branch master https://github.com/scornejob/gpuvmem.git
            - name: Build gpuvmem
              run: cd gpuvmem && mkdir build && cd buid && export PATH=${PATH}:/usr/local/cuda/bin && export LD_LIBRARY_PATH=/usr/local/cuda/lib64 && cmake .. && make -j 8 
